development:
  title: mail2www

  mail_dir: spec/fixtures/mail
  folders:
    - test
    - admin
    - info
    - other

  smtp_server: smtp.example.com
  mailname: example.com
  bounce_to: bounce@example.com
