import { useQuery } from '@tanstack/react-query'
import { Link } from '@tanstack/react-router'
import type { ReactNode } from 'react'
import { api } from './api'
import { DEFAULT_PER_PAGE } from './constants'

export function Layout({ children }: { children: ReactNode }) {
  const config = useQuery({ queryKey: ['config'], queryFn: api.config })
  return <div className="app-shell">
    <header><Link to="/" className="brand">{config.data?.title ?? 'mail2www'}</Link>
      <nav aria-label="Mail folders">{config.data?.folders.map((folder) =>
        <Link key={folder} to="/$folder" params={{ folder }} search={{ page: 0, perPage: DEFAULT_PER_PAGE }} activeProps={{ 'aria-current': 'page' }}>{folder}</Link>
      )}</nav>
    </header>
    {children}
    <footer>Generated by mail2www</footer>
  </div>
}

export function Loading() { return <main className="content status">Loading…</main> }
export function PageError({ error }: { error: Error }) { return <main className="content status error">{error.message}</main> }

export function Pagination({ folder, page, pages, perPage }: { folder: string, page: number, pages: number, perPage: number }) {
  if (pages < 2) return <span />
  return <nav className="pagination" aria-label="Pages">{Array.from({ length: pages }, (_, index) =>
    <Link key={index} to="/$folder" params={{ folder }} search={{ page: index, perPage }} aria-current={index === page ? 'page' : undefined}>{index + 1}</Link>
  )}</nav>
}

const urlPattern = /https?:\/\/[^\s<>]+/g
export function MessageBody({ text, dangerous }: { text: string, dangerous: boolean }) {
  const chunks: ReactNode[] = []
  let offset = 0
  for (const match of text.matchAll(urlPattern)) {
    const index = match.index
    chunks.push(text.slice(offset, index))
    chunks.push(<a key={index} href={match[0]} rel="noreferrer" onClick={(event) => {
      if (dangerous && !window.confirm('This link may be dangerous. Continue?')) event.preventDefault()
    }}>{match[0]}</a>)
    offset = index + match[0].length
  }
  chunks.push(text.slice(offset))
  return <pre className="mail-body">{chunks}</pre>
}
